name: my_cst2335_labs
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  floor: ^1.4.0
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  floor_generator: ^1.4.0
  build_runner: ^2.4.6